name: dm4bem-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.5
  - jupyter=1.0.0
  - jupyterlab=3.6.3
  - ipython=8.15.0
  - matplotlib=3.7.2
  - numpy=1.24.3
  - scipy=1.11.1
  - pandas=2.0.3
