name: dm4bem-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.5
  - jupyter=1.0.0
  - jupyterlab=3.6.3
  - ipython=8.15.0
  - matplotlib=3.7.2
  - numpy=1.24.3
  - scipy=1.11.1
  - pandas=2.0.3
  - ipykernel=6.25.0
  - ipywidgets=8.0.4
  - jupyter_client=7.4.9
  - jupyter_core=5.3.0
  - jupyter_server=1.23.4
  - nbclient=0.5.13
  - nbconvert=6.5.4
  - nbformat=5.9.2
  - notebook=6.5.4
  - qtconsole=5.4.2
  - traitlets=5.7.1
